name: Build and Release

on:
  push:
    tags:
      - 'v*.*.*' 
  workflow_dispatch:  

jobs:
  build:
    runs-on: windows-latest 

    steps:
    - name: Checkout Code
      uses: actions/checkout@v3

    - name: Set up NuGet
      uses: NuGet/setup-nuget@v1.1.1

    - name: Restore NuGet Packages
      run: nuget restore ./Stone\ Manager.csproj

    - name: Build with MSBuild
      run: msbuild ./Stone\ Manager.csproj /p:Configuration=Release

    - name: Archive Build
      uses: actions/upload-artifact@v3
      with:
        name: stone-manager-build
        path: ./bin/Release

  release:
    needs: build
    runs-on: windows-latest
    steps:
    - name: Download Build Artifact
      uses: actions/download-artifact@v3
      with:
        name: stone-manager-build

    - name: Create Release
      uses: softprops/action-gh-release@v1
      with:
        files: './bin/Release/**/*'
      env:
        GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
